version: 0.2

env:
  variables:
    GIT_TAG: $(git describe --tags --exact-match 2>/dev/null)
  parameter-store:
    DOCKERHUB_PASS: "dockerhub-pass"

phases:
  pre_build:
    commands:
      - docker login -u=sumito3478 -p=$DOCKERHUB_PASS
  build:
    commands:
      - docker build -t {REPO_NAME}:{tag} .
      - docker push sumito3478/{REPO_NAME}:{tag}
  post_build:
    commands:
